//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactListWebpage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactListWebpage.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Contact.
        /// </summary>
        public static string add_new_contact {
            get {
                return ResourceManager.GetString("add_new_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Infotype.
        /// </summary>
        public static string add_new_infotype {
            get {
                return ResourceManager.GetString("add_new_infotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string button_create {
            get {
                return ResourceManager.GetString("button_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string button_edit {
            get {
                return ResourceManager.GetString("button_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string button_update {
            get {
                return ResourceManager.GetString("button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Options.
        /// </summary>
        public static string contact_options {
            get {
                return ResourceManager.GetString("contact_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Contact.
        /// </summary>
        public static string create_new_contact {
            get {
                return ResourceManager.GetString("create_new_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string generic_createdat {
            get {
                return ResourceManager.GetString("generic_createdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string generic_example {
            get {
                return ResourceManager.GetString("generic_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string generic_formatting {
            get {
                return ResourceManager.GetString("generic_formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string generic_id {
            get {
                return ResourceManager.GetString("generic_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string generic_name {
            get {
                return ResourceManager.GetString("generic_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string generic_updatedat {
            get {
                return ResourceManager.GetString("generic_updatedat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string generic_value {
            get {
                return ResourceManager.GetString("generic_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotypes.
        /// </summary>
        public static string infotypes {
            get {
                return ResourceManager.GetString("infotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is favorite.
        /// </summary>
        public static string is_favorite {
            get {
                return ResourceManager.GetString("is_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required.
        /// </summary>
        public static string missing_name {
            get {
                return ResourceManager.GetString("missing_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of one contact option is required..
        /// </summary>
        public static string missing_one_or_more {
            get {
                return ResourceManager.GetString("missing_one_or_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string page_contacts {
            get {
                return ResourceManager.GetString("page_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites Overview.
        /// </summary>
        public static string page_favorites {
            get {
                return ResourceManager.GetString("page_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string page_home {
            get {
                return ResourceManager.GetString("page_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string page_homepage {
            get {
                return ResourceManager.GetString("page_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotypes.
        /// </summary>
        public static string page_infotypes {
            get {
                return ResourceManager.GetString("page_infotypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Contact.
        /// </summary>
        public static string update_contact {
            get {
                return ResourceManager.GetString("update_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Options.
        /// </summary>
        public static string user_options {
            get {
                return ResourceManager.GetString("user_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not allowed.
        /// </summary>
        public static string value_not_allowed {
            get {
                return ResourceManager.GetString("value_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is wrongly formatted.
        /// </summary>
        public static string value_wrong_format {
            get {
                return ResourceManager.GetString("value_wrong_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
